// <auto-generated />
namespace AgentsMonitor.DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;

    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ChangedTypeOfSpaceFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ChangedTypeOfSpaceFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201508281006394_ChangedTypeOfSpaceFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return this.Resources.GetString("Target"); }
        }
    }
}
